/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.views;

import core.controllers.AuthController;
import core.controllers.UserController;
import core.controllers.utils.Response;
import core.controllers.utils.Status;
import core.controllers.utils.ViewUtils;
import core.models.entities.Appointment;
import core.models.entities.Doctor;
import core.models.entities.Hospitalization;
import core.models.entities.Patient;
import core.models.entities.User;
import core.models.storage.Storage;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author odvelez
 * @author lvillarreale
 * @author joeltrespalaciosp
 */
public class NewJFrame extends javax.swing.JFrame {

    private int x, y;
    private ArrayList<User> users;
    private ArrayList<Hospitalization> hospitalizations;
    private ArrayList<Appointment> appointments;

    public NewJFrame() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);

        Storage storage = Storage.getInstance();
        this.users = storage.getUsers();
        this.appointments = storage.getAppointments();
        this.hospitalizations = storage.getHospitalizations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new core.views.components.PanelRound();
        pnlTitleBar = new core.views.components.PanelRound();
        btnCloseWindow = new javax.swing.JButton();
        tabLoginRegister = new javax.swing.JTabbedPane();
        pnlLoginContent = new core.views.components.PanelRound();
        lblLoginTitle = new javax.swing.JLabel();
        txtLoginUsername = new javax.swing.JTextField();
        lblLoginUsername = new javax.swing.JLabel();
        txtLoginPassword = new javax.swing.JTextField();
        lblLoginPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        pnlRegisterPatient = new javax.swing.JPanel();
        lblPatientFirstname = new javax.swing.JLabel();
        txtPatientFirstname = new javax.swing.JTextField();
        lblPatientLastname = new javax.swing.JLabel();
        txtPatientLastname = new javax.swing.JTextField();
        lblPatientId = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        lblPatientGender = new javax.swing.JLabel();
        lblPatientPhone = new javax.swing.JLabel();
        txtPatientEmail = new javax.swing.JTextField();
        lblPatientEmail = new javax.swing.JLabel();
        txtPatientPhone = new javax.swing.JTextField();
        lblPatientUsername = new javax.swing.JLabel();
        txtPatientUsername = new javax.swing.JTextField();
        txtPatientPassword = new javax.swing.JTextField();
        lblPatientPassword = new javax.swing.JLabel();
        lblPatientPasswordConfirm = new javax.swing.JLabel();
        txtPatientPasswordConfirm = new javax.swing.JTextField();
        cmbPatientGender = new javax.swing.JComboBox<>();
        btnRegisterPatient = new javax.swing.JButton();
        lblPatientAddress = new javax.swing.JLabel();
        txtPatientAddress = new javax.swing.JTextField();
        lblPatientBirthdate = new javax.swing.JLabel();
        txtPatientBirthdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlRoot.setRadius(50);

        pnlTitleBar.setRadius(50);
        pnlTitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTitleBarMouseDragged(evt);
            }
        });
        pnlTitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTitleBarMousePressed(evt);
            }
        });

        btnCloseWindow.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCloseWindow.setText("X");
        btnCloseWindow.setBorderPainted(false);
        btnCloseWindow.setContentAreaFilled(false);
        btnCloseWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCloseWindow.setFocusable(false);
        btnCloseWindow.setRequestFocusEnabled(false);
        btnCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTitleBarLayout = new javax.swing.GroupLayout(pnlTitleBar);
        pnlTitleBar.setLayout(pnlTitleBarLayout);
        pnlTitleBarLayout.setHorizontalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseWindow)
                .addGap(19, 19, 19))
        );
        pnlTitleBarLayout.setVerticalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCloseWindow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblLoginTitle.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblLoginTitle.setText("LOGIN");

        txtLoginUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLoginUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLoginUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLoginUsername.setText("USERNAME");

        txtLoginPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLoginPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLoginPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLoginPassword.setText("PASSWORD");

        btnLogin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogin.setText("ENTER");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginContentLayout = new javax.swing.GroupLayout(pnlLoginContent);
        pnlLoginContent.setLayout(pnlLoginContentLayout);
        pnlLoginContentLayout.setHorizontalGroup(
            pnlLoginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginContentLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(lblLoginTitle)
                .addGap(481, 481, 481))
            .addGroup(pnlLoginContentLayout.createSequentialGroup()
                .addGroup(pnlLoginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginContentLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(pnlLoginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginContentLayout.createSequentialGroup()
                                .addGroup(pnlLoginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLoginPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLoginUsername, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlLoginContentLayout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(btnLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginContentLayout.setVerticalGroup(
            pnlLoginContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginContentLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblLoginTitle)
                .addGap(74, 74, 74)
                .addComponent(lblLoginUsername)
                .addGap(18, 18, 18)
                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginPassword)
                .addGap(18, 18, 18)
                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnLogin)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        tabLoginRegister.addTab("Login", pnlLoginContent);

        lblPatientFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientFirstname.setText("Firstname");

        txtPatientFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientLastname.setText("Lastname");

        txtPatientLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientId.setText("ID");

        txtPatientId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientGender.setText("Gender");

        lblPatientPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientPhone.setText("Phone");

        txtPatientEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientEmail.setText("Email");

        txtPatientPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientUsername.setText("User");

        txtPatientUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPatientPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientPassword.setText("Password");

        lblPatientPasswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientPasswordConfirm.setText("Password confirmation");

        txtPatientPasswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPatientPasswordConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientPasswordConfirmActionPerformed(evt);
            }
        });

        cmbPatientGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbPatientGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        btnRegisterPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRegisterPatient.setText("Save");
        btnRegisterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPatientActionPerformed(evt);
            }
        });

        lblPatientAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientAddress.setText("Address");

        txtPatientAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientBirthdate.setText("Birthdate");

        txtPatientBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlRegisterPatientLayout = new javax.swing.GroupLayout(pnlRegisterPatient);
        pnlRegisterPatient.setLayout(pnlRegisterPatientLayout);
        pnlRegisterPatientLayout.setHorizontalGroup(
            pnlRegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                .addGroup(pnlRegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(lblPatientPassword))
                    .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(pnlRegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPatientUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(lblPatientUsername))
                    .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(txtPatientPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(btnRegisterPatient))
                    .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(lblPatientPasswordConfirm))
                    .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(pnlRegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                                .addComponent(lblPatientBirthdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPatientBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                                .addComponent(lblPatientFirstname)
                                .addGap(34, 34, 34)
                                .addComponent(txtPatientFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatientLastname)
                            .addComponent(lblPatientAddress))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                                .addComponent(txtPatientLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPatientId)
                                .addGap(30, 30, 30)
                                .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPatientGender)
                                .addGap(26, 26, 26)
                                .addComponent(cmbPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                                .addComponent(txtPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPatientPhone)
                                .addGap(18, 18, 18)
                                .addComponent(txtPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPatientEmail)
                                .addGap(18, 18, 18)
                                .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pnlRegisterPatientLayout.setVerticalGroup(
            pnlRegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterPatientLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlRegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientFirstname)
                    .addComponent(txtPatientFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientLastname)
                    .addComponent(txtPatientLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientId)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientGender)
                    .addComponent(cmbPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPatientBirthdate)
                        .addComponent(txtPatientBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPatientAddress)
                        .addComponent(txtPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPatientPhone)
                        .addComponent(txtPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegisterPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPatientEmail)
                        .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(lblPatientUsername)
                .addGap(18, 18, 18)
                .addComponent(txtPatientUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPatientPassword)
                .addGap(18, 18, 18)
                .addComponent(txtPatientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPatientPasswordConfirm)
                .addGap(18, 18, 18)
                .addComponent(txtPatientPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnRegisterPatient)
                .addGap(42, 42, 42))
        );

        tabLoginRegister.addTab("Patient register", pnlRegisterPatient);

        javax.swing.GroupLayout pnlRootLayout = new javax.swing.GroupLayout(pnlRoot);
        pnlRoot.setLayout(pnlRootLayout);
        pnlRootLayout.setHorizontalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addComponent(tabLoginRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRootLayout.setVerticalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addComponent(pnlTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabLoginRegister)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitleBarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlTitleBarMousePressed

    private void pnlTitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitleBarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_pnlTitleBarMouseDragged

    private void btnCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseWindowActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseWindowActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtLoginUsername.getText();
        String password = txtLoginPassword.getText();

        Response response = AuthController.login(username, password);
        ViewUtils.showResponseMessage(response);

        if (response.getStatus() == Status.OK) {
            openViewForRole(response);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void openViewForRole(Response response) {
        Storage storage = Storage.getInstance();
        User currentUser = storage.getCurrentUser();
        HashMap<String, Object> data = response.getData();
        String role = (String) data.get("role");

        if ("admin".equals(role)) {
            NewJFrame11 admin = new NewJFrame11(currentUser, users, hospitalizations, appointments);
            admin.setVisible(true);
        } else if ("doctor".equals(role)) {
            NewJFrame111 doctor = new NewJFrame111(currentUser, (Doctor) currentUser, users, hospitalizations, appointments);
            doctor.setVisible(true);
        } else if ("patient".equals(role)) {
            NewJFrame1 patient = new NewJFrame1(currentUser, (Patient) currentUser, users, appointments, hospitalizations);
            patient.setVisible(true);
        }
    }

    private void btnRegisterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPatientActionPerformed
        String gender = "";
        if (cmbPatientGender.getSelectedIndex() > 0) {
            gender = cmbPatientGender.getItemAt(cmbPatientGender.getSelectedIndex());
        }

        Response response = UserController.registerPatient(
                txtPatientId.getText(),
                txtPatientFirstname.getText(),
                txtPatientLastname.getText(),
                txtPatientUsername.getText(),
                txtPatientPassword.getText(),
                txtPatientPasswordConfirm.getText(),
                txtPatientEmail.getText(),
                txtPatientBirthdate.getText(),
                txtPatientPhone.getText(),
                txtPatientAddress.getText(),
                gender
        );

        ViewUtils.showResponseMessage(response);

        if (response.getStatus() == Status.CREATED) {
            clearPatientRegisterFields();
        }
    }//GEN-LAST:event_btnRegisterPatientActionPerformed

    private void clearPatientRegisterFields() {
        txtPatientFirstname.setText("");
        txtPatientLastname.setText("");
        txtPatientId.setText("");
        txtPatientEmail.setText("");
        txtPatientPhone.setText("");
        txtPatientUsername.setText("");
        txtPatientPassword.setText("");
        txtPatientPasswordConfirm.setText("");
        txtPatientAddress.setText("");
        txtPatientBirthdate.setText("");
        cmbPatientGender.setSelectedIndex(0);
    }

    private void txtPatientPasswordConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientPasswordConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientPasswordConfirmActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseWindow;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegisterPatient;
    private javax.swing.JComboBox<String> cmbPatientGender;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblPatientUsername;
    private javax.swing.JLabel lblPatientPassword;
    private javax.swing.JLabel lblPatientPasswordConfirm;
    private javax.swing.JLabel lblPatientAddress;
    private javax.swing.JLabel lblPatientBirthdate;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblPatientFirstname;
    private javax.swing.JLabel lblPatientLastname;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPatientGender;
    private javax.swing.JLabel lblPatientPhone;
    private javax.swing.JLabel lblPatientEmail;
    private javax.swing.JPanel pnlRegisterPatient;
    private javax.swing.JTabbedPane tabLoginRegister;
    private javax.swing.JTextField txtLoginUsername;
    private javax.swing.JTextField txtPatientPasswordConfirm;
    private javax.swing.JTextField txtPatientAddress;
    private javax.swing.JTextField txtPatientBirthdate;
    private javax.swing.JTextField txtLoginPassword;
    private javax.swing.JTextField txtPatientFirstname;
    private javax.swing.JTextField txtPatientLastname;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientEmail;
    private javax.swing.JTextField txtPatientPhone;
    private javax.swing.JTextField txtPatientUsername;
    private javax.swing.JTextField txtPatientPassword;
    private core.views.components.PanelRound pnlRoot;
    private core.views.components.PanelRound pnlTitleBar;
    private core.views.components.PanelRound pnlLoginContent;
    // End of variables declaration//GEN-END:variables
}
