/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.views;

import core.controllers.AppointmentController;
import core.controllers.HospitalizationController;
import core.controllers.UserController;
import core.controllers.utils.Response;
import core.controllers.utils.Status;
import core.controllers.utils.ViewUtils;
import core.models.entities.Administrator;
import core.models.entities.Appointment;
import core.models.entities.Hospitalization;
import core.models.entities.Patient;
import core.models.entities.User;
import core.models.storage.Storage;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class NewJFrame1 extends javax.swing.JFrame {

    private int x, y;
    private User user;
    private ArrayList<User> users;
    private Patient patient;
    private ArrayList<Appointment> appointments;
    private ArrayList<Hospitalization> hospitalizations;

    public NewJFrame1(User user,Patient patient, ArrayList<User> users, ArrayList<Appointment>appointments, ArrayList<Hospitalization> hospitalizations) {
        initComponents();
        this.user = user;
        this.users = users;
        this.patient = patient;
        this.hospitalizations = Storage.getInstance().getHospitalizations();
        this.appointments = Storage.getInstance().getAppointments();
        if (user instanceof Administrator) {
            btnBackToAdmin.setVisible(true);
        } else {
            btnBackToAdmin.setVisible(false);
        }
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        loadPatientProfile();
        refreshAppointmentTable();
        loadCancelAppointmentCombo();
        loadHospitalizationCombos();
        refreshAppointmentTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new core.views.components.PanelRound();
        pnlTitleBar = new core.views.components.PanelRound();
        btnCloseWindow = new javax.swing.JButton();
        lblAppTitle = new javax.swing.JLabel();
        btnBackToAdmin = new javax.swing.JButton();
        tabPatientMain = new javax.swing.JTabbedPane();
        pnlHospitalizationSection = new javax.swing.JPanel();
        scrlPatientAppointments = new javax.swing.JScrollPane();
        tblPatientAppointments = new javax.swing.JTable();
        btnRefreshAppointments = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlAppointmentRequestSection = new javax.swing.JPanel();
        lblPatientViewTitle = new javax.swing.JLabel();
        txtPatientFirstname = new javax.swing.JTextField();
        lblPatientProfileTitle = new javax.swing.JLabel();
        txtPatientLastname = new javax.swing.JTextField();
        lblPatientFirstname = new javax.swing.JLabel();
        txtPatientBirthdate = new javax.swing.JTextField();
        lblPatientLastname = new javax.swing.JLabel();
        lblPatientGender = new javax.swing.JLabel();
        txtPatientEmail = new javax.swing.JTextField();
        lblPatientBirthdate = new javax.swing.JLabel();
        txtPatientPhone = new javax.swing.JTextField();
        lblPatientEmail = new javax.swing.JLabel();
        txtPatientAddress = new javax.swing.JTextField();
        txtPatientEmergencyPhone = new javax.swing.JTextField();
        lblPatientPhone = new javax.swing.JLabel();
        lblPatientAddress = new javax.swing.JLabel();
        txtPatientEmergencyContact = new javax.swing.JTextField();
        btnSavePatientProfile = new javax.swing.JButton();
        lblPatientEmergencyPhone = new javax.swing.JLabel();
        txtPatientUsername = new javax.swing.JTextField();
        cmbPatientGender = new javax.swing.JComboBox<>();
        pnlCancelAppointmentSection = new javax.swing.JPanel();
        lblPatientEmergencyContact = new javax.swing.JLabel();
        rbAppointmentBySpecialty = new javax.swing.JRadioButton();
        rbAppointmentByDoctor = new javax.swing.JRadioButton();
        sepPatientAppointments = new javax.swing.JSeparator();
        lblPatientUsername = new javax.swing.JLabel();
        txtAppointmentDate = new javax.swing.JTextField();
        txtAppointmentTime = new javax.swing.JTextField();
        lblHospitalizationAdmissionDate = new javax.swing.JLabel();
        lblHospitalizationDoctor = new javax.swing.JLabel();
        lblHospitalizationRoomType = new javax.swing.JLabel();
        cmbAppointmentType = new javax.swing.JComboBox<>();
        btnRequestAppointment = new javax.swing.JButton();
        sepPatientHospitalization = new javax.swing.JSeparator();
        lblHospitalizationObservations = new javax.swing.JLabel();
        lblHospitalizationReason = new javax.swing.JLabel();
        lblAppointmentTarget = new javax.swing.JLabel();
        cmbHospitalizationDoctor = new javax.swing.JComboBox<>();
        txtHospitalizationAdmissionDate = new javax.swing.JTextField();
        lblAppointmentType = new javax.swing.JLabel();
        lblAppointmentDate = new javax.swing.JLabel();
        cmbHospitalizationRoomType = new javax.swing.JComboBox<>();
        lblAppointmentTime = new javax.swing.JLabel();
        scrlHospitalizationObservations = new javax.swing.JScrollPane();
        txtHospitalizationObservations = new javax.swing.JTextArea();
        btnRequestHospitalization = new javax.swing.JButton();
        lblAppointmentReason = new javax.swing.JLabel();
        lblCancelAppointmentId = new javax.swing.JLabel();
        lblCancelAppointmentObservations = new javax.swing.JLabel();
        scrlAppointmentReason = new javax.swing.JScrollPane();
        txtCancelAppointmentObservations = new javax.swing.JTextArea();
        btnCancelAppointment = new javax.swing.JButton();
        scrlHospitalizationReason = new javax.swing.JScrollPane();
        txtHospitalizationReason = new javax.swing.JTextArea();
        scrlCancelObservations = new javax.swing.JScrollPane();
        txtAppointmentReason = new javax.swing.JTextArea();
        cmbCancelAppointmentId = new javax.swing.JComboBox<>();
        cmbAppointmentDoctorOrSpecialty = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlRoot.setRadius(50);

        pnlTitleBar.setRadius(50);
        pnlTitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTitleBarMouseDragged(evt);
            }
        });
        pnlTitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTitleBarMousePressed(evt);
            }
        });

        btnCloseWindow.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCloseWindow.setText("X");
        btnCloseWindow.setBorderPainted(false);
        btnCloseWindow.setContentAreaFilled(false);
        btnCloseWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCloseWindow.setFocusable(false);
        btnCloseWindow.setRequestFocusEnabled(false);
        btnCloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseWindowActionPerformed(evt);
            }
        });

        lblAppTitle.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblAppTitle.setText("PATIENT VIEW");

        btnBackToAdmin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnBackToAdmin.setText("Back");
        btnBackToAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTitleBarLayout = new javax.swing.GroupLayout(pnlTitleBar);
        pnlTitleBar.setLayout(pnlTitleBarLayout);
        pnlTitleBarLayout.setHorizontalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblAppTitle)
                .addGap(29, 29, 29)
                .addComponent(btnBackToAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseWindow)
                .addGap(19, 19, 19))
        );
        pnlTitleBarLayout.setVerticalGroup(
            pnlTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCloseWindow))
            .addGroup(pnlTitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackToAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblAppTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblPatientAppointments.setAutoCreateRowSorter(true);
        tblPatientAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrlPatientAppointments.setViewportView(tblPatientAppointments);

        btnRefreshAppointments.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRefreshAppointments.setText("Refresh");
        btnRefreshAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshAppointmentsActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHospitalizationSectionLayout = new javax.swing.GroupLayout(pnlHospitalizationSection);
        pnlHospitalizationSection.setLayout(pnlHospitalizationSectionLayout);
        pnlHospitalizationSectionLayout.setHorizontalGroup(
            pnlHospitalizationSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHospitalizationSectionLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(scrlPatientAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(pnlHospitalizationSectionLayout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(btnRefreshAppointments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(78, 78, 78))
        );
        pnlHospitalizationSectionLayout.setVerticalGroup(
            pnlHospitalizationSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHospitalizationSectionLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(scrlPatientAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(pnlHospitalizationSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshAppointments)
                    .addComponent(btnLogout))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        tabPatientMain.addTab("Appointment history", pnlHospitalizationSection);

        lblPatientViewTitle.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientViewTitle.setText("Firstname");

        txtPatientFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientProfileTitle.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientProfileTitle.setText("Lastname");

        txtPatientLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientFirstname.setText("Birthdate");

        txtPatientBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientLastname.setText("Gender");

        lblPatientGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientGender.setText("Email");

        txtPatientEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientBirthdate.setText("Phone");

        txtPatientPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientEmail.setText("Address");

        txtPatientAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPatientEmergencyPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPatientPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientPhone.setText("Password");

        lblPatientAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientAddress.setText("Password confirmation");

        txtPatientEmergencyContact.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        btnSavePatientProfile.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSavePatientProfile.setText("Save");
        btnSavePatientProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePatientProfileActionPerformed(evt);
            }
        });

        lblPatientEmergencyPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientEmergencyPhone.setText("User");

        txtPatientUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        cmbPatientGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbPatientGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        javax.swing.GroupLayout pnlAppointmentRequestSectionLayout = new javax.swing.GroupLayout(pnlAppointmentRequestSection);
        pnlAppointmentRequestSection.setLayout(pnlAppointmentRequestSectionLayout);
        pnlAppointmentRequestSectionLayout.setHorizontalGroup(
            pnlAppointmentRequestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAppointmentRequestSectionLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblPatientViewTitle)
                .addGap(18, 18, 18)
                .addComponent(txtPatientFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblPatientProfileTitle)
                .addGap(18, 18, 18)
                .addGroup(pnlAppointmentRequestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAppointmentRequestSectionLayout.createSequentialGroup()
                        .addComponent(lblPatientBirthdate)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPatientEmail)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlAppointmentRequestSectionLayout.createSequentialGroup()
                        .addComponent(txtPatientLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPatientFirstname)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPatientLastname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblPatientGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(pnlAppointmentRequestSectionLayout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addGroup(pnlAppointmentRequestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAppointmentRequestSectionLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnSavePatientProfile))
                    .addGroup(pnlAppointmentRequestSectionLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txtPatientEmergencyContact, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPatientAddress)
                    .addGroup(pnlAppointmentRequestSectionLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblPatientPhone))
                    .addGroup(pnlAppointmentRequestSectionLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pnlAppointmentRequestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAppointmentRequestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPatientUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlAppointmentRequestSectionLayout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(lblPatientEmergencyPhone)))
                            .addComponent(txtPatientEmergencyPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAppointmentRequestSectionLayout.setVerticalGroup(
            pnlAppointmentRequestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAppointmentRequestSectionLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(pnlAppointmentRequestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientViewTitle)
                    .addComponent(txtPatientFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientProfileTitle)
                    .addComponent(txtPatientLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientFirstname)
                    .addComponent(txtPatientBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientLastname)
                    .addComponent(lblPatientGender)
                    .addComponent(txtPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPatientGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAppointmentRequestSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientBirthdate)
                    .addComponent(txtPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientEmail)
                    .addComponent(txtPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(lblPatientEmergencyPhone)
                .addGap(18, 18, 18)
                .addComponent(txtPatientUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPatientPhone)
                .addGap(18, 18, 18)
                .addComponent(txtPatientEmergencyPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPatientAddress)
                .addGap(18, 18, 18)
                .addComponent(txtPatientEmergencyContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSavePatientProfile)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        tabPatientMain.addTab("Modify info", pnlAppointmentRequestSection);

        lblPatientEmergencyContact.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientEmergencyContact.setText("Request medical appointment");

        rbAppointmentBySpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rbAppointmentBySpecialty.setText("Specialty");
        rbAppointmentBySpecialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAppointmentBySpecialtyActionPerformed(evt);
            }
        });

        rbAppointmentByDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rbAppointmentByDoctor.setText("Doctor");
        rbAppointmentByDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAppointmentByDoctorActionPerformed(evt);
            }
        });

        sepPatientAppointments.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblPatientUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPatientUsername.setText("Appointment date");

        txtAppointmentDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtAppointmentTime.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblHospitalizationAdmissionDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationAdmissionDate.setText("Appointment time");

        lblHospitalizationDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationDoctor.setText("Appointment type");

        lblHospitalizationRoomType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationRoomType.setText("Appointment reason");

        cmbAppointmentType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbAppointmentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Remote", "In-person" }));

        btnRequestAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRequestAppointment.setText("Create");
        btnRequestAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestAppointmentActionPerformed(evt);
            }
        });

        sepPatientHospitalization.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblHospitalizationObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationObservations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalizationObservations.setText("Request hospitalization");

        lblHospitalizationReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblHospitalizationReason.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHospitalizationReason.setText("Hospitalization reason");

        lblAppointmentTarget.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentTarget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointmentTarget.setText("Attending doctor");

        cmbHospitalizationDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbHospitalizationDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        txtHospitalizationAdmissionDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblAppointmentType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointmentType.setText("Estimated date of admission");
        lblAppointmentType.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAppointmentDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointmentDate.setText("Desired room type");

        cmbHospitalizationRoomType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbHospitalizationRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblAppointmentTime.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppointmentTime.setText("Observations");

        txtHospitalizationObservations.setColumns(20);
        txtHospitalizationObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtHospitalizationObservations.setRows(5);
        scrlHospitalizationObservations.setViewportView(txtHospitalizationObservations);

        btnRequestHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRequestHospitalization.setText("Create");
        btnRequestHospitalization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestHospitalizationActionPerformed(evt);
            }
        });

        lblAppointmentReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAppointmentReason.setText("Cancel appointment");

        lblCancelAppointmentId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblCancelAppointmentId.setText("ID appointment");

        lblCancelAppointmentObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblCancelAppointmentObservations.setText("Observations");

        txtCancelAppointmentObservations.setColumns(20);
        txtCancelAppointmentObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtCancelAppointmentObservations.setRows(5);
        scrlAppointmentReason.setViewportView(txtCancelAppointmentObservations);

        btnCancelAppointment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCancelAppointment.setText("Cancel");
        btnCancelAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAppointmentActionPerformed(evt);
            }
        });

        txtHospitalizationReason.setColumns(20);
        txtHospitalizationReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtHospitalizationReason.setRows(5);
        scrlHospitalizationReason.setViewportView(txtHospitalizationReason);

        txtAppointmentReason.setColumns(20);
        txtAppointmentReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAppointmentReason.setRows(5);
        scrlCancelObservations.setViewportView(txtAppointmentReason);

        cmbCancelAppointmentId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbCancelAppointmentId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        cmbAppointmentDoctorOrSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbAppointmentDoctorOrSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout pnlCancelAppointmentSectionLayout = new javax.swing.GroupLayout(pnlCancelAppointmentSection);
        pnlCancelAppointmentSection.setLayout(pnlCancelAppointmentSectionLayout);
        pnlCancelAppointmentSectionLayout.setHorizontalGroup(
            pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                    .addComponent(rbAppointmentBySpecialty)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbAppointmentByDoctor))
                                .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblHospitalizationAdmissionDate)
                                        .addComponent(lblPatientUsername)
                                        .addComponent(cmbAppointmentDoctorOrSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(lblHospitalizationRoomType))
                                .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(lblHospitalizationDoctor))
                                .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(cmbAppointmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(lblPatientEmergencyContact)))
                    .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(scrlCancelObservations, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnRequestAppointment)))
                .addGap(69, 69, 69)
                .addComponent(sepPatientAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(btnRequestHospitalization))
                        .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblHospitalizationReason, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrlHospitalizationReason, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(lblHospitalizationObservations, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(lblAppointmentTarget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCancelAppointmentSectionLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAppointmentTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAppointmentType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(scrlHospitalizationObservations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAppointmentDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(cmbHospitalizationDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(txtHospitalizationAdmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(cmbHospitalizationRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(sepPatientHospitalization, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlAppointmentReason, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                        .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblAppointmentReason))
                            .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnCancelAppointment))
                            .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbCancelAppointmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCancelAppointmentId)))
                            .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lblCancelAppointmentObservations)))
                        .addGap(49, 49, 49)))
                .addGap(81, 81, 81))
        );
        pnlCancelAppointmentSectionLayout.setVerticalGroup(
            pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepPatientAppointments)
            .addComponent(sepPatientHospitalization)
            .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                        .addComponent(lblHospitalizationObservations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(lblHospitalizationReason)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrlHospitalizationReason, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAppointmentTarget)
                        .addGap(18, 18, 18)
                        .addComponent(cmbHospitalizationDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAppointmentType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHospitalizationAdmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblAppointmentDate)
                        .addGap(18, 18, 18)
                        .addComponent(cmbHospitalizationRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAppointmentTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrlHospitalizationObservations, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRequestHospitalization)
                        .addGap(15, 15, 15))
                    .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                        .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                .addComponent(lblPatientEmergencyContact)
                                .addGap(18, 18, 18)
                                .addGroup(pnlCancelAppointmentSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbAppointmentBySpecialty)
                                    .addComponent(rbAppointmentByDoctor))
                                .addGap(18, 18, 18)
                                .addComponent(cmbAppointmentDoctorOrSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPatientUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(lblHospitalizationAdmissionDate)
                                .addGap(18, 18, 18)
                                .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHospitalizationRoomType)
                                .addGap(24, 24, 24)
                                .addComponent(scrlCancelObservations, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCancelAppointmentSectionLayout.createSequentialGroup()
                                .addComponent(lblAppointmentReason)
                                .addGap(39, 39, 39)
                                .addComponent(lblCancelAppointmentId)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCancelAppointmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCancelAppointmentObservations)
                                .addGap(18, 18, 18)
                                .addComponent(scrlAppointmentReason, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnCancelAppointment)))
                        .addGap(18, 18, 18)
                        .addComponent(lblHospitalizationDoctor)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAppointmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnRequestAppointment)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabPatientMain.addTab("Request/Cancel", pnlCancelAppointmentSection);

        javax.swing.GroupLayout pnlRootLayout = new javax.swing.GroupLayout(pnlRoot);
        pnlRoot.setLayout(pnlRootLayout);
        pnlRootLayout.setHorizontalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPatientMain)
        );
        pnlRootLayout.setVerticalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addComponent(pnlTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPatientMain))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitleBarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlTitleBarMousePressed

    private void pnlTitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTitleBarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_pnlTitleBarMouseDragged

    private void btnCloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseWindowActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseWindowActionPerformed

    private void btnCancelAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAppointmentActionPerformed
        String appointmentId = (String) cmbCancelAppointmentId.getSelectedItem();
        Response response = AppointmentController.cancelAppointment(
                patient.getId(),
                appointmentId,
                txtCancelAppointmentObservations.getText());
        ViewUtils.showResponseMessage(response);
        if (response.getStatus() == Status.OK) {
            txtCancelAppointmentObservations.setText("");
            loadCancelAppointmentCombo();
            refreshAppointmentTable();
        }
    }//GEN-LAST:event_btnCancelAppointmentActionPerformed

    private void btnSavePatientProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePatientProfileActionPerformed
        String gender = (String) cmbPatientGender.getSelectedItem();
        Response response = UserController.updatePatient(
                patient.getId(),
                txtPatientFirstname.getText(),
                txtPatientLastname.getText(),
                txtPatientUsername.getText(),
                txtPatientEmergencyPhone.getText(),
                txtPatientEmergencyContact.getText(),
                txtPatientEmail.getText(),
                txtPatientBirthdate.getText(),
                txtPatientPhone.getText(),
                txtPatientAddress.getText(),
                gender);
        ViewUtils.showResponseMessage(response);
    }//GEN-LAST:event_btnSavePatientProfileActionPerformed

    private void loadPatientProfile() {
        Response response = UserController.getPatientProfile(patient.getId());
        if (response.getStatus() != Status.OK || response.getData() == null) {
            return;
        }
        HashMap<String, Object> data = response.getData();
        txtPatientFirstname.setText((String) data.get("firstname"));
        txtPatientLastname.setText((String) data.get("lastname"));
        txtPatientBirthdate.setText((String) data.get("birthdate"));
        txtPatientEmail.setText((String) data.get("email"));
        txtPatientPhone.setText((String) data.get("phone"));
        txtPatientAddress.setText((String) data.get("address"));
        txtPatientUsername.setText((String) data.get("username"));
        String genderDisplay = (String) data.get("gender");
        for (int i = 0; i < cmbPatientGender.getItemCount(); i++) {
            if (cmbPatientGender.getItemAt(i).equals(genderDisplay)) {
                cmbPatientGender.setSelectedIndex(i);
                break;
            }
        }
    }

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        ViewUtils.performLogout(this);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackToAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToAdminActionPerformed
        ArrayList<User> currentUsers = Storage.getInstance().getUsers();
        ArrayList<Hospitalization> currentHospitalizations = Storage.getInstance().getHospitalizations();
        ArrayList<Appointment> currentAppointments = Storage.getInstance().getAppointments();
        NewJFrame11 admin = new NewJFrame11(user, currentUsers, currentHospitalizations, currentAppointments);
        this.setVisible(false);
        admin.setVisible(true);
    }//GEN-LAST:event_btnBackToAdminActionPerformed

    private void rbAppointmentBySpecialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAppointmentBySpecialtyActionPerformed
        if (rbAppointmentByDoctor.isSelected()) {
            rbAppointmentByDoctor.setSelected(false);
        }
        fillComboFromResponse(cmbAppointmentDoctorOrSpecialty, AppointmentController.getSpecialtyComboOptions());
    }//GEN-LAST:event_rbAppointmentBySpecialtyActionPerformed

    private void rbAppointmentByDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAppointmentByDoctorActionPerformed
        if (rbAppointmentBySpecialty.isSelected()) {
            rbAppointmentBySpecialty.setSelected(false);
        }
        fillComboFromResponse(cmbAppointmentDoctorOrSpecialty, AppointmentController.getDoctorComboOptions());
    }//GEN-LAST:event_rbAppointmentByDoctorActionPerformed

    private void btnRequestAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestAppointmentActionPerformed
        boolean byDoctor = rbAppointmentByDoctor.isSelected();
        String comboSelection = (String) cmbAppointmentDoctorOrSpecialty.getSelectedItem();
        String appointmentType = (String) cmbAppointmentType.getSelectedItem();
        Response response = AppointmentController.requestAppointment(
                patient.getId(),
                byDoctor,
                comboSelection,
                txtAppointmentDate.getText(),
                txtAppointmentTime.getText(),
                txtAppointmentReason.getText(),
                appointmentType);
        ViewUtils.showResponseMessage(response);
        if (response.getStatus() == Status.CREATED) {
            clearAppointmentRequestFields();
            refreshAppointmentTable();
            loadCancelAppointmentCombo();
            this.appointments = Storage.getInstance().getAppointments();
        }
    }//GEN-LAST:event_btnRequestAppointmentActionPerformed

    private void btnRefreshAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshAppointmentsActionPerformed
        refreshAppointmentTable();
    }//GEN-LAST:event_btnRefreshAppointmentsActionPerformed

    private DefaultTableModel createPatientAppointmentTableModel() {
        return new DefaultTableModel(
                new Object[0][0],
                new String[]{"ID", "Date", "Doctor", "Specialty", "Type", "Status"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
    }

    private DefaultTableModel createPatientHospitalizationTableModel() {
        return new DefaultTableModel(
                new Object[0][0],
                new String[]{"ID", "Date", "Doctor", "Room", "Status", "Reason"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
    }

    private void populateTableFromRows(DefaultTableModel model, List<?> rows, String[] columnKeys) {
        model.setRowCount(0);
        for (Object rowObject : rows) {
            if (rowObject instanceof HashMap) {
                HashMap<?, ?> row = (HashMap<?, ?>) rowObject;
                Object[] values = new Object[columnKeys.length];
                for (int i = 0; i < columnKeys.length; i++) {
                    values[i] = row.get(columnKeys[i]);
                }
                model.addRow(values);
            }
        }
    }

    private void refreshAppointmentTable() {
        Response response = AppointmentController.listPatientAppointments(patient.getId());
        if (response.getStatus() != Status.OK || response.getData() == null) {
            return;
        }
        Object rowsObject = response.getData().get("rows");
        if (!(rowsObject instanceof List)) {
            return;
        }
        List<?> rows = (List<?>) rowsObject;
        DefaultTableModel model = createPatientAppointmentTableModel();
        populateTableFromRows(model, rows, new String[]{"id", "date", "doctor", "specialty", "type", "status"});
        tblPatientAppointments.setModel(model);
    }

    private void refreshPatientHospitalizationTable() {
        Response response = HospitalizationController.listPatientHospitalizations(patient.getId());
        if (response.getStatus() != Status.OK || response.getData() == null) {
            return;
        }
        Object rowsObject = response.getData().get("rows");
        if (!(rowsObject instanceof List)) {
            return;
        }
        List<?> rows = (List<?>) rowsObject;
        DefaultTableModel model = createPatientHospitalizationTableModel();
        populateTableFromRows(model, rows, new String[]{"id", "date", "doctor", "roomType", "status", "reason"});
        tblPatientAppointments.setModel(model);
    }

    private void loadCancelAppointmentCombo() {
        fillComboFromResponse(cmbCancelAppointmentId, AppointmentController.listCancellableAppointmentIds(patient.getId()));
    }

    private void fillComboFromResponse(javax.swing.JComboBox<String> combo, Response response) {
        combo.removeAllItems();
        if (response.getStatus() != Status.OK || response.getData() == null) {
            combo.addItem("Select one");
            return;
        }
        Object optionsObject = response.getData().get("options");
        if (optionsObject instanceof ArrayList) {
            ArrayList<?> options = (ArrayList<?>) optionsObject;
            for (Object option : options) {
                if (option != null) {
                    combo.addItem(option.toString());
                }
            }
        } else {
            combo.addItem("Select one");
        }
    }

    private void clearAppointmentRequestFields() {
        txtAppointmentDate.setText("");
        txtAppointmentTime.setText("");
        txtAppointmentReason.setText("");
        cmbAppointmentType.setSelectedIndex(0);
        cmbAppointmentDoctorOrSpecialty.removeAllItems();
        cmbAppointmentDoctorOrSpecialty.addItem("Select one");
        rbAppointmentBySpecialty.setSelected(false);
        rbAppointmentByDoctor.setSelected(false);
    }

    private void btnRequestHospitalizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestHospitalizationActionPerformed
        String doctorSelection = (String) cmbHospitalizationDoctor.getSelectedItem();
        String roomTypeDisplay = (String) cmbHospitalizationRoomType.getSelectedItem();
        Response response = HospitalizationController.requestHospitalization(
                patient.getId(),
                doctorSelection,
                txtHospitalizationAdmissionDate.getText(),
                txtHospitalizationReason.getText(),
                roomTypeDisplay,
                txtHospitalizationObservations.getText());
        ViewUtils.showResponseMessage(response);
        if (response.getStatus() == Status.CREATED) {
            clearHospitalizationRequestFields();
            this.hospitalizations = Storage.getInstance().getHospitalizations();
            refreshPatientHospitalizationTable();
            tabPatientMain.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnRequestHospitalizationActionPerformed

    private void loadHospitalizationCombos() {
        fillComboFromResponse(cmbHospitalizationDoctor, AppointmentController.getDoctorComboOptions());
        fillComboFromResponse(cmbHospitalizationRoomType, HospitalizationController.getRoomTypeComboOptions());
    }

    private void clearHospitalizationRequestFields() {
        txtHospitalizationReason.setText("");
        txtHospitalizationObservations.setText("");
        txtHospitalizationAdmissionDate.setText("");
        cmbHospitalizationDoctor.setSelectedIndex(0);
        cmbHospitalizationRoomType.setSelectedIndex(0);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseWindow;
    private javax.swing.JButton btnRequestAppointment;
    private javax.swing.JButton btnRequestHospitalization;
    private javax.swing.JButton btnCancelAppointment;
    private javax.swing.JButton btnRefreshAppointments;
    private javax.swing.JButton btnBackToAdmin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSavePatientProfile;
    private javax.swing.JComboBox<String> cmbAppointmentType;
    private javax.swing.JComboBox<String> cmbHospitalizationDoctor;
    private javax.swing.JComboBox<String> cmbHospitalizationRoomType;
    private javax.swing.JComboBox<String> cmbCancelAppointmentId;
    private javax.swing.JComboBox<String> cmbAppointmentDoctorOrSpecialty;
    private javax.swing.JComboBox<String> cmbPatientGender;
    private javax.swing.JLabel lblAppTitle;
    private javax.swing.JLabel lblPatientPhone;
    private javax.swing.JLabel lblPatientAddress;
    private javax.swing.JLabel lblPatientEmergencyPhone;
    private javax.swing.JLabel lblPatientEmergencyContact;
    private javax.swing.JLabel lblPatientUsername;
    private javax.swing.JLabel lblHospitalizationAdmissionDate;
    private javax.swing.JLabel lblHospitalizationDoctor;
    private javax.swing.JLabel lblHospitalizationRoomType;
    private javax.swing.JLabel lblHospitalizationObservations;
    private javax.swing.JLabel lblHospitalizationReason;
    private javax.swing.JLabel lblPatientViewTitle;
    private javax.swing.JLabel lblAppointmentTarget;
    private javax.swing.JLabel lblAppointmentType;
    private javax.swing.JLabel lblAppointmentDate;
    private javax.swing.JLabel lblAppointmentTime;
    private javax.swing.JLabel lblAppointmentReason;
    private javax.swing.JLabel lblCancelAppointmentId;
    private javax.swing.JLabel lblCancelAppointmentObservations;
    private javax.swing.JLabel lblPatientProfileTitle;
    private javax.swing.JLabel lblPatientFirstname;
    private javax.swing.JLabel lblPatientLastname;
    private javax.swing.JLabel lblPatientGender;
    private javax.swing.JLabel lblPatientBirthdate;
    private javax.swing.JLabel lblPatientEmail;
    private javax.swing.JPanel pnlAppointmentRequestSection;
    private javax.swing.JPanel pnlCancelAppointmentSection;
    private javax.swing.JPanel pnlHospitalizationSection;
    private javax.swing.JRadioButton rbAppointmentBySpecialty;
    private javax.swing.JRadioButton rbAppointmentByDoctor;
    private javax.swing.JScrollPane scrlHospitalizationObservations;
    private javax.swing.JScrollPane scrlAppointmentReason;
    private javax.swing.JScrollPane scrlPatientAppointments;
    private javax.swing.JScrollPane scrlHospitalizationReason;
    private javax.swing.JScrollPane scrlCancelObservations;
    private javax.swing.JSeparator sepPatientAppointments;
    private javax.swing.JSeparator sepPatientHospitalization;
    private javax.swing.JTabbedPane tabPatientMain;
    private javax.swing.JTable tblPatientAppointments;
    private javax.swing.JTextArea txtHospitalizationObservations;
    private javax.swing.JTextArea txtCancelAppointmentObservations;
    private javax.swing.JTextArea txtHospitalizationReason;
    private javax.swing.JTextArea txtAppointmentReason;
    private javax.swing.JTextField txtPatientFirstname;
    private javax.swing.JTextField txtPatientEmergencyContact;
    private javax.swing.JTextField txtPatientUsername;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextField txtAppointmentTime;
    private javax.swing.JTextField txtHospitalizationAdmissionDate;
    private javax.swing.JTextField txtPatientLastname;
    private javax.swing.JTextField txtPatientBirthdate;
    private javax.swing.JTextField txtPatientEmail;
    private javax.swing.JTextField txtPatientPhone;
    private javax.swing.JTextField txtPatientAddress;
    private javax.swing.JTextField txtPatientEmergencyPhone;
    private core.views.components.PanelRound pnlRoot;
    private core.views.components.PanelRound pnlTitleBar;
    // End of variables declaration//GEN-END:variables
}
